# Generated by Django 4.2.1 on 2023-08-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledblynkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sensordata',
            table='SensorData',
        ),
    ]
