# Generated by Django 4.2.1 on 2023-08-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledblynkapp', '0002_alter_sensordata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='pin',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='value',
            field=models.IntegerField(),
        ),
    ]
